# Plotly and Cufflinks
- Plotly is a python library used to create interactive graphs.

- Cufflinks connects plotly with pandas to create graphs and charts of dataframes directly.

In [4]:
!pip install plotly
!pip install cufflinks

Requirement already satisfied: plotly in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (7.1.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from plotly) (26.3)
Collecting cufflinks
  Downloading cufflinks-0.17.3.tar.gz (81 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.9.2 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from cufflinks) (2.3.5)
Requirement already satisfied: pandas>=0.19.2 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from cufflinks) (2.3.3)
Requirement already satisfied: plotly>=4.1.1 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from cufflinks) (7.1.0)
Requirement already satisfied: six>=1.9.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from cufflinks) (1.17.0)
Collecting colorlover>=0.2.1 (from cufflinks)
  Downloading colorlover-0.3.0-py3-none-any.whl.metadata (421 bytes)
Requirement already satisfied: setuptools>=34.4.1 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from cufflinks) (80.10.2)
Requirement already satisfied: ipython>=5.3.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from cufflinks) (9.17.1)
Requirement already satisfied: ipywidgets>=7.0.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from cufflinks) (8.1.9)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.53)
Requirement already satisfied: psutil>=7 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipython>=5.3.0->cufflinks) (5.16.1)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.8.3)
Requirement already satisfied: comm>=0.1.3 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.16 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.17)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from jedi>=0.18.2->ipython>=5.3.0->cufflinks) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from pandas>=0.19.2->cufflinks) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from pandas>=0.19.2->cufflinks) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from pandas>=0.19.2->cufflinks) (2026.3)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from plotly>=4.1.1->cufflinks) (2.26.0)
Requirement already satisfied: packaging in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from plotly>=4.1.1->cufflinks) (26.3)
Requirement already satisfied: executing>=1.2.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\panch\anaconda3\envs\dataanalysis\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (0.2.3)
Downloading colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Building wheels for collected packages: cufflinks
  Building wheel for cufflinks (pyproject.toml): started
  Building wheel for cufflinks (pyproject.toml): finished with status 'done'
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68561 sha256=595c7ffccfa4da454891f7b54f8e0816a212201b8231e8a6916b66b2e71edfb6
  Stored in directory: c:\users\panch\appdata\local\pip\cache\wheels\c0\d9\70\372130dacf508192607c1a7359c7bf0656b1a3b79f6cf66f7a
Successfully built cufflinks
Installing collected packages: colorlover, cufflinks

   -------------------- ------------------- 1/2 [cufflinks]
   ---------------------------------------- 2/2 [cufflinks]

Successfully installed colorlover-0.3.0 cufflinks-0.17.3

In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from plotly.offline import iplot
import cufflinks as cf
import plotly.express as px

In [6]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [19]:


fig=px.line(df, y="tip")
fig.show()

In [20]:

fig = px.bar(df, y="tip")
fig.show()

In [22]:
fig = px.scatter(df,y='total_bill')
fig.show()

In [25]:
fig = px.histogram(df,y=['sex'])
fig.show()

In [28]:
fig = px.box(df,y=['tip'])
fig.show()

In [29]:
df.head(1)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

In [40]:
fig = px.pie(df['total_bill'],df['day'])
fig.show()